name: Story
description: Write a story describing a feature you want implemented.
title: ""
labels: ["question"]
projects: ["Andrei15193/5"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill a feature request as a user story!

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: email@example.com
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the core idea in a few words.
      placeholder: |
        As a user
        I want to do this thing
        So that the app is more useful
      value: |
        **As a** role
        **I want to** action
        **So that** result
    validations:
      required: true

  - type: textarea
    id: acceptanceCriteria
    attributes:
      label: Acceptance Criteria
      description: Describe use cases for this feature, add as many as you like.
      placeholder: |
        **Given** that I am viewing hints
        **When** I click on a button
        **Then** I will be performing this action
      value: |
        **Given** state
        **When** action
        **Then** result
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: Details
      description: Are there more details you would like to add?
      placeholder: |
        List out things that are not covered in the acceptance criteria
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Any wireframes, images or other useful information you would like to add.
    validations:
      required: false