name: Build & Deploy HintKeep

on:
  push:
    branches:
      - vNext

concurrency:
  group: test
  cancel-in-progress: true

jobs:
  buildWebClient:
    name: Build WebClient
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Restore
        working-directory: WebClient
        run: npm install

      - name: Test
        working-directory: WebClient
        run: npm run test

      - name: Build
        working-directory: WebClient
        run: npm run build-release

      - name: Pack
        shell: pwsh
        working-directory: WebClient
        run: |
          $ErrorActionPreference = 'Stop'

          Get-ChildItem `
            -Path 'publish' `
          | Compress-Archive `
            -DestinationPath (Join-Path '..' 'WebClient.zip') `
            -CompressionLevel Optimal `
          | Out-Null

      - name: Publish Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: WebClient.zip

  buildGraphQL:
    name: Build GraphQL
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Dotnet 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x

      - name: Test
        shell: pwsh
        working-directory: GraphQL
        run: |
          dotnet test `
            --configuration Debug

      - name: Build
        shell: pwsh
        working-directory: GraphQL
        run: |
          dotnet publish ./HintKeep.GraphQL.csproj `
            --configuration Release `
            --runtime linux-x64 `
            --no-self-contained `
            --output publish

      - name: Pack
        shell: pwsh
        working-directory: GraphQL
        run: |
          $ErrorActionPreference = 'Stop'

          Get-ChildItem `
            -Path 'publish' `
          | Compress-Archive `
            -DestinationPath (Join-Path '..' 'GraphQL.zip') `
            -CompressionLevel Optimal `
          | Out-Null

          Get-ChildItem `
            -Path 'publish' `
            -Hidden `
          | Compress-Archive `
            -DestinationPath (Join-Path '..' 'GraphQL.zip') `
            -CompressionLevel Optimal `
            -Update `
          | Out-Null

      - name: Publish Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: GraphQL.zip

  deployment:
    needs:
      - buildWebClient
      - buildGraphQL
    name: Deployment on Test
    runs-on: ubuntu-latest
    environment: Test
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: build

      # REQUIRED: setup service principal for deploying bicep & function apps
      #
      # - name: Deploy GraphQL
      #   shell: pwsh
      #   run: |
      #     $ErrorActionPreference = 'Stop'

      #     $azureResources = az deployment sub create `
      #       --name 'hintkeep-test' `
      #       --location 'westeurope' `
      #       --parameters (Join-Path '.infrastructure' 'Environments' 'test.bicepparam') `
      #       --query 'properties.outputs' `
      #     | ConvertFrom-Json

      #     az functionapp deployment source config-zip `
      #       --name $azureResources.functionsAppName.value `
      #       --resource-group $azureResources.resourceGroupName.value `
      #       --src ./GraphQL.zip `
      #       --build-remote false `
      #     | Out-Null

      - name: Deploy WebClient
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'

          Invoke-RestMethod `
            -Method Post `
            -Uri 'https://api.netlify.com/api/v1/sites/${{ vars.SITE_ID }}/deploys' `
            -ContentType 'application/zip' `
            -Authentication Bearer `
            -Token (ConvertTo-SecureString -AsPlainText '${{ secrets.DEPLOY_TOKEN }}') `
            -InFile WebClient.zip `
          | Out-Null