name: Build
on:
  push:
    branches: 
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: |
        npm install
        dotnet restore

    - name: Build
      run: |
        npm run build -- --mode=production
        dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal

    - name: Generate Publish Output
      if: github.event_name == 'push' && contains(toJSON(github.event.commits.*.message), '[release]')
      run: dotnet publish ./HintKeep/HintKeep.csproj --configuration Release --output ./Publish/HintKeep

    - name: Generate Deployment Package
      if: github.event_name == 'push' && contains(toJSON(github.event.commits.*.message), '[release]')
      shell: pwsh
      working-directory: ./Publish/HintKeep
      run: |
        rm appsettings.Development.json
        zip -r ../HintKeep.zip .

    - name: Azure Authentication
      if: github.event_name == 'push' && contains(toJSON(github.event.commits.*.message), '[release]')
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Application
      if: github.event_name == 'push' && contains(toJSON(github.event.commits.*.message), '[release]')
      shell: pwsh
      run: |
        az webapp stop --resource-group HintKeep --name HintKeep
        az webapp deployment source config-zip --resource-group HintKeep --name HintKeep --src ./Publish/HintKeep.zip
        az webapp start --resource-group HintKeep --name HintKeep